apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-2hsf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-2hsf
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-2hsf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-2hsf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-2hsf
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-kwgp-tenant/rhtap-demo-app/hacbs-test-project-2hsf@sha256:d19c9a3e589f9969f8a94f760355979f720fd082c522e619728325a5cfd34aed
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
